### PR TITLE
Generate an LALR(1) parser

### PR DESCRIPTION
**Pull request by kemitchell**
Here it is, my current proposal. A handwritten tokenizer (lexer) emits INDENT and OUTDENT tokens, with column and line tracking. Jison, the JavaScript Bison clone, generates the parser from a Bison-style BNF grammar file.

The syntax is slightly different than past proposals and current commonform-markup:

``` commonform
# New syntax
Paragraph text

  \ First Heading \ child form content

  \ Another Heading !! Conspicuous content

  \\ child without heading

  \!! conspicuous child without heading
```

I went to two total backslashes per child, since `\\\\` failed to grow on me.

Apart from the new heading syntax, there is one additional and significant change affecting content at the top level within a file. Long story short, the old parser handled content like this as special cases:

``` commonform
# Old syntax, would become invalid
Paragraph text

\\ Child of the top-level form
```

Equivalent content would now be typed:

``` commonform
# New syntax
Paragraph text

    \\ Child of the top-level form
```

This has the nice side effect of avoiding unintuitive, ambiguous looking situations like:

``` commonform
# Old syntax, would become invalid
Paragraph text

\\ Child of the top-level form

Is this top-level text after the child form, or a continuation of the child form?
```

@anseljh, @rickcolosimo, @tbrooke: I would very much appreciate any and all thoughts. The tentative plan is to bring the master branch of commonform-new-markup into the commonform-markup repository as an orphan branch and release as commonform-markup@1.0.0 once we also have a decision on what to do about commonform/commonform-validate#5.

Editor syntax files, like vim-commonform's, will need to be updated. So will the sample files and template examples.

### CODE REVIEW

**Comment by kemitchell** [comment]
Would close #1

**Comment by kemitchell** [comment]
https://github.com/commonform/vim-commonform/commit/fb1238138b53824d11f474d243b41cc597c809d0 updates vim syntax highlighting.

**Comment by kemitchell** [comment]
On second thought, this would be released as new commonform-markup-parse.

**Comment by tbrooke** [comment]
So the double backslash remains at the top level?

 Would the following be right?

```
 Corporate Offices \\

     Offices \\ In addition to the corporation's registered office set forth in the Certificate ...

 \Main Office\ Main Office on Main Street
 \Second Office\ Second Office off Main Street
    \\There may be other offices we don't know about 
```

Corporate Offices
1. Offices.  In addition to the  to the corporation's registered office set forth in the Certificate ...
   
      a. Main Office Main Office on Main Street
   
      b. Second Office Second Office off Main Street
   
      c. There may be other offices we don't know about

**Comment by kemitchell** [comment]
@tbrooke not quite. Corrected:

``` commonform
 \Corporate Offices\

     \Offices\ In addition to the corporation's registered office set forth in the Certificate ...

 \Main Office\ Main Office on Main Street
 \Second Office\ Second Office off Main Street
    \\There may be other offices we don't know about 
```

The parser expects at most two backslashes per child form.

**Pull request closed without merging**
